name: Pull Docker Image Based on Text File

on: [workflow_dispatch]

jobs:
  pull-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read text file and extract image and arguments
        id: read-config
        run: |
          while IFS=": " read -r key value
          do
            # Trim any leading/trailing whitespace from the key and value
            key=$(echo $key | xargs)
            value=$(echo $value | xargs)
            
            if [[ $key == 'image' ]]; then
              image_name=$value
              echo "::set-output name=image_name::$image_name"
              echo "DEBUG: Image name is $image_name"
            elif [[ $key == 'arguments' ]]; then
              image_arguments=$value
              echo "::set-output name=image_arguments::$image_arguments"
              echo "DEBUG: Image arguments are $image_arguments"
            else
              echo "DEBUG: Unrecognized key '$key' with value '$value'"
            fi
          done < image.txt


      - name: Pull Docker Image
        run: |
          docker pull ${{ steps.read-config.outputs.image_name }}

      - name: Run Docker Image with Arguments
        run: |
          docker run ${{ steps.read-config.outputs.image_arguments }} ${{ steps.read-config.outputs.image_name }}

      - name: Check Docker Images
        run: |
          docker images
