name: Pull Docker Image Based on Text File

on: [workflow_dispatch]

jobs:
  pull-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read text file and extract image and arguments
        id: read-config
        run: |
          while IFS= read -r line
          do
            # Remove carriage returns that might be present in a Mac-created file
            line=$(echo "$line" | tr -d '\r')

            # Split the line into key and value based on the first colon followed by a space
            key=$(echo $line | cut -d ':' -f 1 | xargs)
            value=$(echo $line | cut -d ':' -f 2- | xargs)

            echo "DEBUG: Key is '$key', Value is '$value'"

            if [[ $key == 'image' ]]; then
              image_name=$value
              echo "::set-output name=image_name::$image_name"
            elif [[ $key == 'arguments' ]]; then
              image_arguments=$value
              echo "::set-output name=image_arguments::$image_arguments"
            fi
          done < image.txt



      - name: Pull Docker Image
        run: |
          docker pull ${{ steps.read-config.outputs.image_name }}

      - name: Run Docker Image with Arguments
        run: |
          docker run ${{ steps.read-config.outputs.image_arguments }} ${{ steps.read-config.outputs.image_name }}

      - name: Check Docker Images
        run: |
          docker images
