name: Pull Docker Image Based on Text File

on: [workflow_dispatch]

jobs:
  pull-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read text file and extract image and arguments
        id: read-config
        run: |
          while IFS= read -r line
          do
            if [[ $key == 'image' ]]; then
              echo "::set-output name=image_name::$image_name"
            elif [[ $key == 'arguments' ]]; then
              echo "::set-output name=image_arguments::$image_arguments"
            fi
          done < image.txt



      - name: Pull Docker Image
        run: |
          docker pull ${{ steps.read-config.outputs.image_name }}

      - name: Run Docker Image with Arguments
        run: |
          docker run ${{ steps.read-config.outputs.image_name }} ${{ steps.read-config.outputs.image_arguments }}

      - name: Check Docker Images
        run: |
          docker images
